buildscript {
    repositories {
        maven { url = "https://files.minecraftforge.net/maven" }
        maven { url = "https://repo.spongepowered.org/repository/maven-public/" }
    }
    dependencies {
        classpath group: "net.minecraftforge.gradle", name: "ForgeGradle", version: "6.0.+", changing: true
        classpath group: "org.spongepowered", name: "mixingradle", version: "0.7-SNAPSHOT"
    }
}

apply plugin: "net.minecraftforge.gradle"
apply plugin: "eclipse"
apply plugin: "maven-publish"
apply plugin: "org.spongepowered.mixin"

group = mod_group_id
version = "${minecraft_version}-${mod_version}"
base {
    archivesName = mod_id
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(17)
}

mixin {
    add sourceSets.main, "${mod_id}.refmap.json"
    //config "${mod_id}.mixins.json"
}

minecraft {
    mappings channel: "official", version: minecraft_version
    accessTransformer = file("src/main/resources/META-INF/accesstransformer.cfg")

    runs {
        // applies to all the run configs below
        configureEach {
            workingDirectory project.file('run')

            /*Recommended logging data for a userdev environment
            The markers can be added/remove as needed separated by commas.
            "SCAN": For mods scan.
            "REGISTRIES": For firing of registry events.
            "REGISTRYDUMP": For getting the contents of all registries.*/
            property "forge.logging.markers", "SCAN,REGISTRIES,REGISTRYDUMP"

            /*Recommended logging level for the console
            You can set various levels here.
            Please read: https://stackoverflow.com/questions/2031163/when-to-use-the-different-log-levels*/
            property "forge.logging.console.level", "debug"

            property "mixin.env.remapRefMap", "true"
            property "mixin.env.refMapRemappingFile", "${projectDir}/build/createSrgToMcp/output.srg"

            mods {
                "${mod_id}" {
                    source sourceSets.main
                }
            }
        }

        client {
            // Comma-separated list of namespaces to load gametests from. Empty = all namespaces.
            property 'forge.enabledGameTestNamespaces', mod_id
            arg "-mixin.config=" + mod_id + ".mixins.json"
        }

        server {
            property 'forge.enabledGameTestNamespaces', mod_id
            arg "-mixin.config=" + mod_id + ".mixins.json"
            args '--nogui'
        }

        data {
            property "blueprint.indev", "true"

            // Specify the modid for data generation, where to output the resulting resource, and where to look for existing resources.
            //args "--mod", mod_id, "--all", "--output", file("src/generated/resources/"), "--existing", file("src/main/resources/"), "--existing-mod", "blueprint", "--existing-mod", "buzzier_bees"
            args '--mod', mod_id, '--all', '--output', file('src/generated/resources/'), '--existing', file('src/main/resources/'), "--existing-mod", "blueprint"
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

dependencies {

    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"
    //implementation is used when you want to use a mod as a library, and the mod is required to run the game.
    implementation fg.deobf("com.teamabnormals:blueprint:${minecraft_version}-${blueprint_version}")
    implementation fg.deobf("com.teamabnormals:woodworks:${minecraft_version}-${woodworks_version}")
    implementation fg.deobf("com.teamabnormals:boatload:${minecraft_version}-${boatload_version}")

    //compileOnly is used when you want to use a mod as a library, but the mod is not required to run the game, and only needed at compile time.
    //compileOnly fg.deobf("maven.modrinth:what-are-you-voting-for-2023:aGgzILtB")
    compileOnly fg.deobf("mezz.jei:jei-${minecraft_version}-common-api:${jei_version}")
    compileOnly fg.deobf("mezz.jei:jei-${minecraft_version}-forge-api:${jei_version}")

    //runtimeOnly is used when you want to use a mod as a library, but the mod is not required to run the game, and only needed at runtime.
    runtimeOnly fg.deobf("mezz.jei:jei-${minecraft_version}-forge:${jei_version}")

    annotationProcessor "org.spongepowered:mixin:0.8.5:processor"

    compileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:0.5.0"))
    implementation(jarJar("io.github.llamalad7:mixinextras-forge:0.5.0")) {
        jarJar.ranged(it, "[0.5.0,)")
    }

}

repositories {
    maven { url "https://maven.teamabnormals.com" }
    maven { url "https://dvs1.progwml6.com/files/maven/" }
    maven { url "https://modmaven.k-4u.nl" }
    maven { url "https://www.cursemaven.com" }
    exclusiveContent {
        forRepository {
            maven {
                name = "Modrinth"
                url = "https://api.modrinth.com/maven"
            }
        }
        forRepositories(fg.repository) // Only add this if you're using ForgeGradle, otherwise remove this line
        filter {
            includeGroup "maven.modrinth"
        }
    }
}

tasks.named('jar', Jar).configure {
    manifest {
        attributes(["Specification-Title"     : mod_id,
                    "Specification-Vendor"    : mod_authors,
                    "Specification-Version"   : "1", // We are version 1 of ourselves
                    "Implementation-Title"    : mod_name,
                    "Implementation-Version"  : mod_version,
                    "Implementation-Vendor"   : mod_authors,
                    "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ"),
                    "MixinConfigs"            : mod_id + ".mixins.json"
        ])

    }
    // finalizedBy just run the reobfJar task after building the jar.
    //finalizedBy 'reobfJar'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
}