org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)

forge_version=47.1.3
forge_version_range=[47,)
loader_version_range=[47,)

mapping_channel=official
mapping_version=1.20.1

blueprint_version=7.1.0
blueprint_version_range=[7.1.0,)
boatload_version=5.0.1
woodworks_version=3.0.1
jei_version=15.3.0.4

mod_id=artifully
mod_name=ArtiFully
mod_license=All Rights Reserved
mod_version=1.0-SNAPSHOT
mod_group_id=com.tfp
mod_authors=TheFeralP
mod_description=A mod focused on bringing new blocks and items with great utilities for building, decoration, and survival within the world
